version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: microtrack
      MONGO_INITDB_ROOT_PASSWORD: microtrack
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
